version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "02:00"
  open-pull-requests-limit: 3
  groups:
    python-dependencies:
      patterns:
        - "*"

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: monthly
    time: "02:00"
  open-pull-requests-limit: 3
  groups:
    github-actions-dependencies:
      patterns:
        - "*"
